### ISSUE TITLE
SecurityException: Requires READ_PHONE_STATE in IabHelper

### ISSUE THREAD

**Issue by maxim-yudin** [googlesamples/android-play-billing#26]
I began to get some crash reposting with this exception

java.lang.SecurityException: Requires READ_PHONE_STATE: Neither user 10088 nor current process has android.permission.READ_PHONE_STATE.
    at android.os.Parcel.readException(Parcel.java:1546)
    at android.os.Parcel.readException(Parcel.java:1499)
    at com.android.vending.billing.IInAppBillingService$Stub$Proxy.getSkuDetails(IInAppBillingService.java:299)
    at IabHelper.querySkuDetails(IabHelper.java:939)

**Comment by nrichards** [comment]
I'm seeing reports of this too:
* http://forum.unity3d.com/threads/iap-crash-for-very-few-customers-crash-log-points-to-read_phone_state-permission.413942/
* https://code.google.com/p/android/issues/detail?id=214680 / https://productforums.google.com/forum/#!topic/play/4LigT3eyQgk
* https://code.google.com/p/android/issues/detail?id=214808
* http://stackoverflow.com/questions/38131475/in-android-java-lang-securityexception

Could this be a combination of: 1) Android N with its Dynamic Permissions model, and 2) normal application bugs where the app uses a permission but doesn't ask the user to grant access? .... No, this Android Billing issue is not one which should exercise an app-code bug...it smells like a change in the Play Store. 

Puzzling!

**Comment by friedger** [comment]
Could this be related to policy guard in CM? Google Play services always assume that they have the permission they requested at install time.

**Comment by velis74** [comment]
I can't be sure, but I updated the SDK just before publishing latest version of my app (which now crashes on SOME devices, but not all). I think that play store library was also among the updates.

Maybe there was a change in the library code that now requires this permission?

**Comment by jkane001** [comment]
Seeing this as well.

**Comment by friedger** [comment]
Can you reproduce the issue with this andoid-play-billing app?

**Comment by zevektor** [comment]
I'm seeing this kind of error in my application as well. Not on all devices, mainly on Android 4.* versions.

**Comment by jkane001** [comment]
And it's definitely random... I've gotten it once in the past few days, but had hundreds of iab events with just fine.

**Comment by Mikhael-Danilov** [comment]
Same error in my app.

Observed on Android 5.1 and 4.0.4

**Comment by sdeff** [comment]
Same here.

<img width="1050" alt="bildschirmfoto 2016-07-18 um 02 41 21" src="https://cloud.githubusercontent.com/assets/2885756/16904168/37ab689e-4c91-11e6-9bcc-b270e0dac599.png">

**Comment by er-mo** [comment]
Same for me!

**Comment by timr-github** [comment]
We are also seeing this issue as described in our apps

**Comment by ManuelPeinado** [comment]
Same problem here, started around 3 weeks ago. 

Devices affected:
![image](https://cloud.githubusercontent.com/assets/2700015/16921992/268b230a-4d14-11e6-8393-c6ff0d796e62.png)

OS versions:
![image](https://cloud.githubusercontent.com/assets/2700015/16922013/36944056-4d14-11e6-86a9-0956216c9a8d.png)

**Comment by MattHamersky** [comment]
Just chiming in that this is happening to us as well, started the same time as everyone else, been spiking significantly the few days (in the 1000's as opposed to the 100's).


![screen shot 2016-07-18 at 2 11 18 pm](https://cloud.githubusercontent.com/assets/3959377/16930569/befb4a16-4cf1-11e6-8af9-7f2e7d79c3af.png)

OS:
![screen shot 2016-07-18 at 2 11 39 pm](https://cloud.githubusercontent.com/assets/3959377/16930588/c8b10064-4cf1-11e6-97ca-3dde36b619d1.png)

Devices:
![screen shot 2016-07-18 at 2 11 49 pm](https://cloud.githubusercontent.com/assets/3959377/16930602/d2a8b6d4-4cf1-11e6-9811-683b227ec766.png)

**Comment by mosess** [comment]
+1

**Comment by nrichards** [comment]
Do any of these crash reporting tools provide *version information* for Google Play services / Play Store app? Or a repro device which could be used to collect those values from?

(Programmatically, [PackageInfo](https://developer.android.com/reference/android/content/pm/PackageInfo.html) can pull version, [example](http://stackoverflow.com/a/8052835/915990).)

**Comment by MattHamersky** [comment]
@nrichards Our crash reporting tool (hockeyapp) only provides the stacktraces, devices affected, and OS versions.  Playe Services/Play Store app version information is included in our own analytics calls but we can't link analytics calls to device crashes in hockeyapp.

**Comment by Howie64** [comment]
I have this exact same issue on my Archos 55 Platinum while playing Pokemon Go.
As soon as I open Activities related to vending the app crashes.
The version of the Google Play-Services is: 9.2.56 (230-124593566)
The version of the Google Play Store is: 6.7.13.E-all [0] 2920566

After deinstalling the updates I got:
Google Play-Services version : 7.5.71 (1955121-436)

It still didn't work.

The device is stock exept for activated developer options.

If there is anything I can test, I can do it tomorrow.

**Comment by stoyicker** [comment]
I can't provide Play Store version because we have not managed to reproduce it in-house, but these are the devices that most frequently have the crash in [our app](https://play.google.com/store/apps/details?id=se.feomedia.quizkampen.de.lite):

![screenshot from 2016-07-20 09-13-56](https://cloud.githubusercontent.com/assets/1732935/16978114/7f41127e-4e5a-11e6-889d-b6244200828b.png)

**Comment by xiphirx** [comment]
Hi everyone, we contacted Google directly about this issue and they just got back to us saying they have identified the issue and are working on resolving it immediately. Should be fixed soon!

**Comment by am1n** [comment]
Hi I am also seeing this on Android 4.x and 5.x devices. @xiphirx thanks for the update, does this appear to be a Google Play Services issue or an issue with the licensing library?

**Comment by xiphirx** [comment]
It appears to be a Google play services issue

**Comment by xiphirx** [comment]
Update: Google has fixed the issue, it should be rolled out to affected devices by Saturday.

**Comment by chriswiesner** [comment]
still having crashes here. although it seems to be for only a few users.
anyone else still having issues?

**Comment by evgenez** [comment]
Re: "_we contacted Google directly about this issue and they just got back to us saying they have identified the issue and are working on resolving it immediately_"

Could anyone please comment officially:
1) What is the issue # (any reference at all)?
2) What version of Google Play/Google Play Services this was fixed in?

We still seeing the issue, not sure what to advise the users who have issues with IAP.

**Comment by ashughes** [comment]
I'd also like to know how you contacted Google directly. Is there an official channel to report billing issues? Issue #2 has been around for years. I've reached out to two Google contacts I met at I/O who said they'd look into the issue, but unfortunately I haven't heard back from either of them.

**Comment by xiphirx** [comment]
There is no official channel to report issues in that I'm aware of outside of emailing Google's support. 

The company I work for has a line of communication to their dev ops support team, which is who I reported the issue to. 

Here's a graph of the crashes happening for our app before and after the fix:
![image](https://cloud.githubusercontent.com/assets/993832/17192344/e29e4e42-5402-11e6-9d60-42ab442f26b5.png)

So yes, there are a few crashes lingering around. I believe this issue is device / manufacturer specific, so in the interest of fixing it entirely, lets compile a list of devices that are showing the crash _after_ the 25th. I can then send/link the list to Google and hopefully it will be resolved.

That, or Google can pay attention to this issue... :(

**Comment by raethlein** [comment]
Seeing the same issue: 
![image](https://cloud.githubusercontent.com/assets/3775781/17294001/284287ca-57f4-11e6-8790-c52c843fdb8e.png)

**Comment by mosess** [comment]
@xiphirx, Devices that we've encountered this crash on, later than the 25th (Model and OS version):
4033L	4.2.2
C2005	4.3
C6833	5.1.1
C6902	5.1.1
Che2-L11	4.4.2
D6502	6.0.1
GT-I9063T	4.2.2
GT-I9300	4.3
GT-I9515	5.0.1
GT-N5120	4.2.2
GT-P3100	4.1.2
H60-L04	6
Hol-U19	4.4.2
HTC One E9PLUS dual sim	5.0.2
HUAWEI GRA-UL10	5.0.1
HUAWEI SCL-U31	5.1.1
Infinix-X551	4.4.2
Lenovo A3000-H	4.2.2
LenovoA3300-GV	4.4.2
LG-H818	6
LS-5010	5.1.1
LT25i	4.1.2
Micromax A106	5
MID	5.1.1
nfinix-X551	4.4.2
SHV-E250L	4.4.2
SM-A500H	4.4.4
SM-G900F	5
SM-G900H	5
SM-G920F	6.0.1
SM-G925F	6.0.1
SM-G928C	6.0.1
SM-G935F	6.0.1
SM-N900	5
SM-N910C	5.1.1
SM-N910C	6.0.1
SM-N910G	6.0.1
SM-N910H	5.1.1
SM-N9200	6.0.1
SM-N920C	6.0.1
SM-P555 	5.0.2
SM-P601	        4.4.2

**Comment by enginebai** [comment]
I've faced the same problem. Is there any solution yet?
<img width="1375" alt="2016-08-09 9 52 31" src="https://cloud.githubusercontent.com/assets/3387462/17502027/1ba834fa-5e17-11e6-8392-863800361d7b.png">

**Comment by yamoinza** [comment]
We just started seeing this crash as we ramped our new release.
Predominantly occurring on 4.4.2 but also occurs on 5.1.

**Comment by am1n** [comment]
Still happening for my app at irregular intervals but seems to be only on Android 4.4.2.

**Comment by enginebai** [comment]
Yes, the crash seems to be only on Android 4.4.2.
<img width="1136" alt="2016-08-17 4 25 49" src="https://cloud.githubusercontent.com/assets/3387462/17729573/68f2500c-6497-11e6-87c8-3a65fbe2855d.png">

**Comment by maxim-yudin** [comment]
Some additional information about this crash. It occurs for particular devices and OS versions. Sorry for russian screenshot. It's from Firebase crash reporting of my app.

<img width="1135" alt="2016-08-18 7 07 44" src="https://cloud.githubusercontent.com/assets/3336671/17761753/f211707e-651a-11e6-8967-ee53a35b0e70.png">

**Comment by zevektor** [comment]
Hello Everyone. 

I have a question: is this error only restricted to async operations? If yes, why not using IntentService+BroadcastReceiver to perform the inventory check asynchronously?

**Comment by rpattabi** [comment]
Got this crash on Lava A89 / Android 5.1 / API 22. So this is not limited to 4.4.2

**Comment by zevektor** [comment]
Can this be related to rooted devices only?

**Comment by enginebai** [comment]
@zevektor No, most of crashes happened on non-rooted devices. (In my crash report, there are 10% happening on rooted devices)

**Comment by netomarin** [comment]
This issue was fixed as reported.
And because this issue is not exactly related to this sample, I'm closing the issue.
Next time you have technical question, feel free to make a question on Stackoverflow and use the tags google-play, in-app-purchase or in-app-billing.
Thanks.
